// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7wNcDcHRCzCcq_NzcpFWNl2cfsfwRGs',
    appId: '1:917614781066:web:174403cabd9c0f994bc373',
    messagingSenderId: '917614781066',
    projectId: 'laundrycaps2',
    authDomain: 'laundrycaps2.firebaseapp.com',
    storageBucket: 'laundrycaps2.firebasestorage.app',
    measurementId: 'G-P9YSX88TEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsI4JZl4uYXjzULXsUPcgBlaIvyTUbwKI',
    appId: '1:917614781066:android:307e2673f9bce3ad4bc373',
    messagingSenderId: '917614781066',
    projectId: 'laundrycaps2',
    storageBucket: 'laundrycaps2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lRk5xkbFG9-8TwSe0HIMh3o4FfAZNpE',
    appId: '1:917614781066:ios:2f43f99dd10273024bc373',
    messagingSenderId: '917614781066',
    projectId: 'laundrycaps2',
    storageBucket: 'laundrycaps2.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4lRk5xkbFG9-8TwSe0HIMh3o4FfAZNpE',
    appId: '1:917614781066:ios:2f43f99dd10273024bc373',
    messagingSenderId: '917614781066',
    projectId: 'laundrycaps2',
    storageBucket: 'laundrycaps2.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq7wNcDcHRCzCcq_NzcpFWNl2cfsfwRGs',
    appId: '1:917614781066:web:be0c670fd0ba17fb4bc373',
    messagingSenderId: '917614781066',
    projectId: 'laundrycaps2',
    authDomain: 'laundrycaps2.firebaseapp.com',
    storageBucket: 'laundrycaps2.firebasestorage.app',
    measurementId: 'G-K2Z478P2WR',
  );
}
